-- 1. CONFIGURAÇÃO INICIAL
DROP DATABASE IF EXISTS `Copercogg`;
CREATE SCHEMA IF NOT EXISTS `Copercogg` DEFAULT CHARACTER SET utf8mb4;
USE `Copercogg`;

SET sql_safe_updates = 0;

-- 2. CRIAÇÃO DAS TABELAS
DROP TABLE IF EXISTS CLIENTES;
-- Tabela Clientes
CREATE TABLE IF NOT EXISTS `CLIENTES` (
  `id_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `SEXO` CHAR(1) NOT NULL,
  `DATA_DE_NASCIMENTO` DATE NULL,
  PRIMARY KEY (`id_CLIENTE`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE
) ENGINE = InnoDB;


-- Tabela Endereço Físico
CREATE TABLE IF NOT EXISTS `ENDERECO_FISICO` (
  `id_ENDERECO_FISICO` INT NOT NULL AUTO_INCREMENT,
  `PAIS` VARCHAR(45) NULL,
  `UF` VARCHAR(50) NULL,
  `CIDADE` VARCHAR(45) NULL,
  `BAIRRO` VARCHAR(45) NULL,
  `RUA` VARCHAR(45) NULL,
  `CEP` VARCHAR(8) NULL CHECK (CEP REGEXP '^[0-9]{8}$'),
  `id_CLIENTE` INT NULL,
  PRIMARY KEY (`id_ENDERECO_FISICO`),
  INDEX `fk_ENDERECO_CLIENTES_idx` (`id_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_CLIENTES`
    FOREIGN KEY (`id_CLIENTE`)
    REFERENCES `CLIENTES` (`id_CLIENTE`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `ENDERECO_DIGITAL` (
  `id_ENDERECO_DIGITAL` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(255) NOT NULL,
  `EMAIL_OPCIONAL` VARCHAR(255) NULL,
  `TELEFONE` VARCHAR(45) NULL,
  `id_CLIENTE` INT NULL,
  PRIMARY KEY (`id_ENDERECO_DIGITAL`),
  UNIQUE INDEX `uq_EMAIL` (`EMAIL` ASC),
  UNIQUE INDEX `uq_EMAIL_OPCIONAL` (`EMAIL_OPCIONAL` ASC),
  UNIQUE INDEX `uq_TELEFONE` (`TELEFONE` ASC),
  INDEX `fk_ENDERECO_DIGITAL_CLIENTES_idx` (`id_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_DIGITAL_CLIENTES1`
    FOREIGN KEY (`id_CLIENTE`)
    REFERENCES `CLIENTES` (`id_CLIENTE`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Tabela Cogumelos (Produtos)
CREATE TABLE IF NOT EXISTS `COGUMELOS` (
  `id_COGUMELOS` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(110) NULL,
  `TIPO` TINYTEXT NULL,
  `PRECO_KG` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_COGUMELOS`),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC) VISIBLE
) ENGINE = InnoDB;


-- preco=peso em pedidos * preço base do cogumelo 
-- Tabela Pedidos
CREATE TABLE IF NOT EXISTS `PEDIDOS` (
  `idPEDIDOS` INT NOT NULL AUTO_INCREMENT,
  `PESO` DECIMAL(10,2),
  `DATA_PEDIDO` DATETIME DEFAULT CURRENT_TIMESTAMP ,    
  `PRECO_TOTAL` DECIMAL(9,2),
  `DATA_ENTREGA` DATE,
  `NOME_CLIENTE` VARCHAR(100) NULL,
  `NOME_PRODUTO` VARCHAR(110),
  `STATUS` VARCHAR(25) DEFAULT 'PENDENTE',
  `id_CLIENTE` INT,
  PRIMARY KEY (`idPEDIDOS`),
  CONSTRAINT `fk_PEDIDOS_CLIENTES`
    FOREIGN KEY (`id_CLIENTE`)
    REFERENCES `CLIENTES` (`id_CLIENTE`)
    ON DELETE CASCADE
) ENGINE = InnoDB;


-- Tabela Estoque
CREATE TABLE IF NOT EXISTS `ESTOQUE` (
  `id_ESTOQUE` INT NOT NULL AUTO_INCREMENT,
  `PESO_ATUAL` DECIMAL(10,2) UNSIGNED NULL,
  `id_COGUMELOS` INT NULL,
  PRIMARY KEY (`id_ESTOQUE`),
  INDEX `fk_ESTOQUE_COGUMELOS_idx` (`id_COGUMELOS` ASC) VISIBLE,
  CONSTRAINT `fk_ESTOQUE_COGUMELOS`
    FOREIGN KEY (`id_COGUMELOS`)
    REFERENCES `COGUMELOS` (`id_COGUMELOS`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- depois usar encrypt
CREATE TABLE IF NOT EXISTS `usuarios`(
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NULL,
  `tipo` VARCHAR(40) NULL,
  `senha` VARCHAR(100),
  PRIMARY KEY (`id_usuario`)
);


-- //Só deixa esses insert e aquele update
INSERT INTO usuarios (login, tipo, senha)
VALUES ('admin_master', 'Administrador', 'senha123');

INSERT INTO usuarios (login, tipo, senha)
VALUES ('op_1', 'Operador', 'senha1234');

UPDATE usuarios
SET senha = SHA2(senha, 256);